---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# High-Dimensional Multivariate Bayesian Variable and Covariance Selection in Linear Regression 

### SME0809 - Inferência Bayesiana
#### Grupo 13
    - Heitor Carvalho Pinheiro
    - Francisco Rosa Dias de Miranda
  
  
---
    

Com o desenvolvimento de técnicas de alto processamento na biologia molecular, a caracterização molecular em alta escala tornou-se um lugar comum, com o advento de técnicas como:

 - genome-wide measurement of gene expression
 - single nucleotide polymorphisms
 - CpG methylation status
 - pharmacological profiling for large-scale cancer drug screen.
 
A análise de associações conjuntas entre múltiplos fenótipos correlacionados e atributos moleculares de alta dimensionalidade é desafiadora.

---

Quando múltiplos fenótipos e informação genômica de alta dimensionalidade são analisados conjuntamente, a abordagem bayesiana permite especificar de maneira flexível as relações complexas entre os conjunto de dados altamente estruturados.

O pacote `BayesSUR` combina diversos modelos que foram propostos para a regressão multidimentional com resposta múltipla e introduz um novo modelo, que permite diferentes *prioris* na seleção de variáveis dos modelos de regressão e para diferentes pressupostos a respeito da estrutura de dependência entre as respostas.

---

## Especificação dos modelos

 - múltiplas opções de seleção de variáveis
 - a matriz de covariância pode ser diagonal, densa ou esparsa.
 
 O modelo de regressão é escrito como:
 
 $$\boldsymbol{Y} = \boldsymbol{XB} + \boldsymbol{U}$$
 $$\text{vec}{(\boldsymbol{U})} \sim \mathcal{N}(\boldsymbol{0}, C \otimes \mathbb{I}_n) $$

onde:
 - $\boldsymbol{Y}$ é uma matriz $n \times s$ das variáveis resposta com matriz de covariância C;
 - 


https://www.statlect.com/matrix-algebra/Kronecker-product