% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={SME0820 - Modelos de Regressão e Aprendizado Supervisionado I - Exercício 2},
  pdfauthor={Brenda da Silva Muniz 11811603; Francisco Rosa Dias de Miranda 4402962; Heitor Carvalho Pinheiro 11833351; Mônica Amaral Novelli 11810453},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{SME0820 - Modelos de Regressão e Aprendizado Supervisionado I -
Exercício 2}
\author{Brenda da Silva Muniz 11811603 \and Francisco Rosa Dias de Miranda 4402962 \and Heitor Carvalho Pinheiro 11833351 \and Mônica Amaral Novelli 11810453}
\date{Novembro 2021}

\begin{document}
\maketitle

\hypertarget{exercuxedcio-4}{%
\section{Exercício 4}\label{exercuxedcio-4}}

Queremos mostrar que o estimador \(F_0\) pode ser escrito na forma
\(F_0 = \frac{R^2(n-p)}{k(1-R^2)}\)

Note que podemos escrever \(SQ_{reg} = SQ_{total} R^2\). Por definição,
temos que

\[\begin{aligned}
F_0 = \frac{QM_{reg}}{QM_{res}} = \frac{\frac{SQ_{reg}}{k}}{\frac{SQ_{res}}{n-p}} = \frac{SQ_{reg}}{SQ_{res}} \frac{n-p}k = \frac{SQ_{total}\ R^2}{SQ_{total} - SQ_{reg}}  \frac{n-p}{k} = \\
\frac{SQ_{total}\ R^2}{SQ_{total} - SQ_{total}\ R^2}  \frac{n-p}{k} = 
\frac{SQ_{total}\ R^2}{SQ_{total} ( 1- R^2)}  \frac{n-p}{k} = \\
\frac{R^2(n-p)}{k (1- R^2)}.
\end{aligned}\]

Portanto, os dois são equivalentes.

\#Exercício 5

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Usando o exercício 4, teste a significância da regressão com
  \(\alpha = 0.05\)
\end{enumerate}

Do exercício anterior temos que: \[F_0 = \frac{R^2(n-p)}{k (1- R^2)}\]

Para \(k = 2\), \(n = 25\), \(p=k+1\) e \(R^2 = 0.90\):
\[F_0 = \frac{0.9(25-3)}{2 (1- 0.9)} = 99\]

Podemos calcular \(F_{(0.95,2,22)}\) com o seguinte comando:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#calculando o valor crítico de F(0.95,2,22)}
\KeywordTok{qf}\NormalTok{(}\FloatTok{0.95}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{22}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.443357
\end{verbatim}

Logo, \(F_{(0.95,2,22)} \approx 3.443\).

Como, \(F_0 > F_{(0.95,2,22)}\), rejeitamos \(H_0\) em favor de \(H_1\)
e concluímos que o modelo testado é significante para \(\alpha = 0.05\).
Isto é, ele capta melhor a tendência dos dados se comparado ao modelo
restrito, \(y = \beta_0 + \epsilon\).

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Qual o menor valor de \(R^2\) para que o modelo seja significativo?
\end{enumerate}

Como no item anterior, vamos considerar um nível de significância
\(\alpha = 0.05\).

Sabemos que o modelo será significante se, e somente se,
\(F_0 > F_{(0.95,2,22)}\). Isso implica que:
\[\frac{R^2(n-p)}{k (1- R^2)} > 3.443\] Logo, segue que:

\[\frac{R^2(25-3)}{2 (1- R^2)} > 3.443 \\
R^2>0.2383\]

Portanto, considerando apenas dois algarismos significativos, podemos
considerar que o valor mínimo de \(R^2\) para que o modelo possa ser
considerado significativo é \(R^2 = 0.24\)

\hypertarget{exercuxedcio-11}{%
\section{Exercício 11}\label{exercuxedcio-11}}

\hypertarget{conjunto-de-dados}{%
\subsection{Conjunto de dados}\label{conjunto-de-dados}}

O dataset contém dados de um experimento para determinar \textbf{tempo},
\textbf{temperatura}, \textbf{percentual de solvatação},
\textbf{rendimento de óleo} e \textbf{carvão total} sob o
\textbf{rendimento (y)}

Significância: 97\%

Leitura dos pacotes utilizados:

Leitura do pacote de dados:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readr)}
\NormalTok{dados <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"data-table-B5.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 27 Columns: 8
\end{verbatim}

\begin{verbatim}
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## dbl (8): y, x1, x2, x3, x4, x5, x6, x7
\end{verbatim}

\begin{verbatim}
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{View}\NormalTok{(dados)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Renomeando as colunas}
\KeywordTok{names}\NormalTok{(dados) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'y'}\NormalTok{, }\StringTok{'Tempo'}\NormalTok{, }\StringTok{'Temperatura'}\NormalTok{, }\StringTok{'Perc_solvatação'}\NormalTok{, }\StringTok{'Rendimento_Òleo'}\NormalTok{, }\StringTok{'Carvão_Total'}\NormalTok{,}\StringTok{'x6'}\NormalTok{,}\StringTok{'x7'}\NormalTok{)}
\KeywordTok{head}\NormalTok{(dados)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##       y Tempo Temperatura Perc_solvatação Rendimento_Òleo Carvão_Total    x6
##   <dbl> <dbl>       <dbl>           <dbl>           <dbl>        <dbl> <dbl>
## 1 37.0    5.1         400            51.4            4.24        1485. 2227.
## 2 13.7   26.4         400            72.3           30.9          290.  435.
## 3 10.1   23.8         400            71.4           33.0          321.  481.
## 4  8.53  46.4         400            79.2           44.6          165.  247.
## 5 36.4    7           450            80.5           33.8         1097. 1646.
## 6 26.6   12.6         450            89.9           41.3          605.  908.
## # ... with 1 more variable: x7 <dbl>
\end{verbatim}

Para facilitar nosso trabalho em termos computacionais, estaremos
nomeando nossas variáveis e criando um data frame com as mesmas; sendo:

\begin{itemize}
\item
  \(Y:\) Rendimento total de azeite por lote de amendoim*
\item
  \(X_1:\) Tempo
\item
  \(X_2:\) Temperatura
\item
  \(X_3:\) Perc\_solvatação
\item
  \(X_4:\) Rendimento\_Òleo
\item
  \(X_5:\) Carvão\_Total
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x1 <-}\StringTok{ }\NormalTok{dados}\OperatorTok{$}\NormalTok{Tempo}
\NormalTok{x2 <-}\StringTok{ }\NormalTok{dados}\OperatorTok{$}\NormalTok{Temperatura}
\NormalTok{x3 <-}\StringTok{ }\NormalTok{dados}\OperatorTok{$}\NormalTok{Perc_solvatação}
\NormalTok{x4 <-}\StringTok{ }\NormalTok{dados}\OperatorTok{$}\NormalTok{Rendimento_Òleo}
\NormalTok{x5 <-}\StringTok{ }\NormalTok{dados}\OperatorTok{$}\NormalTok{Carvão_Total}
\NormalTok{y <-}\StringTok{ }\NormalTok{dados}\OperatorTok{$}\NormalTok{y}

\NormalTok{tabela01 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(x1, x2, x3, x4, x5, y))}
\NormalTok{tabela01}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      x1  x2    x3    x4      x5     y
## 1   5.1 400 51.37  4.24 1484.83 36.98
## 2  26.4 400 72.33 30.87  289.94 13.74
## 3  23.8 400 71.44 33.01  320.79 10.08
## 4  46.4 400 79.15 44.61  164.76  8.53
## 5   7.0 450 80.47 33.84 1097.26 36.42
## 6  12.6 450 89.90 41.26  605.06 26.59
## 7  18.9 450 91.48 41.88  405.37 19.07
## 8  30.2 450 98.60 70.79  253.70  5.96
## 9  53.8 450 98.05 66.82  142.27 15.52
## 10  5.6 400 55.69  8.92 1362.24 56.61
## 11 15.1 400 66.29 17.98  507.65 26.72
## 12 20.3 400 58.94 17.79  377.60 20.80
## 13 48.4 400 74.74 33.94  158.05  6.99
## 14  5.8 425 63.71 11.95  130.66 45.93
## 15 11.2 425 67.14 14.73  682.59 43.09
## 16 27.9 425 77.65 34.49  274.20 15.79
## 17  5.1 450 67.22 14.48 1496.51 21.60
## 18 11.7 450 81.48 29.69  652.43 35.19
## 19 16.7 450 83.88 26.33  458.42 26.14
## 20 24.8 450 89.38 37.98  312.25  8.60
## 21 24.9 450 79.77 25.66  307.08 11.63
## 22 39.5 450 87.93 22.36  193.61  9.59
## 23 29.0 450 79.50 31.52  155.96  4.42
## 24  5.5 460 72.73 17.86 1392.08 38.89
## 25 11.5 450 77.88 25.20  663.09 11.19
## 26  5.2 470 75.50  8.66 1464.11 75.62
## 27 10.6 470 83.15 22.39  720.07 36.03
\end{verbatim}

Devido à complexidade das fórmulas envolvidas para realizarmos uma
regressão linear múltima, utilizaremos uma abordagem matricial. Desse
modo, poderemos escrever

\$y\_i = \beta\_0 + \beta\emph{1 x}\{1i\} + \beta\emph{2 x}\{2i\} +
\ldots{} + \beta\emph{k x}\{ki\} + \varepsilon\_i, i = 1, \ldots, 5. \$

como:

\(y_1 = \beta_0 + \beta_1 x_{11} + \beta_2 x_{21} + ... + \beta_k x_{k1} + \varepsilon_1\)
\(y_2 = \beta_0 + \beta_1 x_{12} + \beta_2 x_{22} + ... + \beta_k x_{k2} + \varepsilon_2\)
\(y_3 = \beta_0 + \beta_1 x_{13} + \beta_2 x_{23} + ... + \beta_k x_{k3} + \varepsilon_3\)
\(y_4 = \beta_0 + \beta_1 x_{14} + \beta_2 x_{24} + ... + \beta_k x_{k4} + \varepsilon_4\)
\(y_5 = \beta_0 + \beta_1 x_{15} + \beta_2 x_{25} + ... + \beta_k x_{k5} + \varepsilon_5\)

Assim, alocamos essas equações em dois vetores colunas (5x1), fazendo:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(dados}\OperatorTok{$}\NormalTok{y)}
\NormalTok{X <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,n), x1, x2, x3, x4, x5), }\DataTypeTok{ncol =} \DecValTok{6}\NormalTok{, }\DataTypeTok{nrow =}\NormalTok{ n, }\DataTypeTok{byrow =} \OtherTok{FALSE}\NormalTok{)}
\NormalTok{Y <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(y, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{, }\DataTypeTok{nrow =}\NormalTok{ n)}
\NormalTok{k <-}\StringTok{ }\KeywordTok{ncol}\NormalTok{(X) }\DecValTok{-1}
\NormalTok{p <-}\StringTok{ }\NormalTok{k }\OperatorTok{+}\StringTok{ }\DecValTok{1}
\end{Highlighting}
\end{Shaded}

**

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Definindo os betas do modelo de regressão múltipla}

\NormalTok{betas <-}\StringTok{ }\KeywordTok{solve}\NormalTok{(}\KeywordTok{t}\NormalTok{(X)}\OperatorTok{%*%}\NormalTok{X)}\OperatorTok{%*%}\KeywordTok{t}\NormalTok{(X)}\OperatorTok{%*%}\NormalTok{Y}

\CommentTok{#Definindo a matrix C_jj}

\NormalTok{C_jj =}\StringTok{ }\KeywordTok{solve}\NormalTok{(}\KeywordTok{t}\NormalTok{(X)}\OperatorTok{%*%}\NormalTok{X)}

\CommentTok{#Definindo uma matrix para os betas}

\NormalTok{betas <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ betas, }\DataTypeTok{nrow =} \KeywordTok{length}\NormalTok{(betas), }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{, }\DataTypeTok{byrow =} \OtherTok{FALSE}\NormalTok{)}
\KeywordTok{rownames}\NormalTok{(betas) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"beta0"}\NormalTok{, }\StringTok{"beta1"}\NormalTok{,}\StringTok{"beta2"}\NormalTok{,}\StringTok{"beta3"}\NormalTok{,}\StringTok{"beta4"}\NormalTok{,}\StringTok{"beta5"}\NormalTok{)}
\NormalTok{betas}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              [,1]
## beta0 30.59319595
## beta1 -0.38612042
## beta2 -0.04556211
## beta3  0.31074404
## beta4 -0.37167815
## beta5  0.01409776
\end{verbatim}

Abaixo, estaremos conferindo com os valores dos betas calculados pelo
método lm. É importante ressaltar que não chamaremos o data frame do
conjunto de dados completo - visto que esse conta com as variáveis
\(x_6\) e \(x_7\) que não serão consideradas nessa análise de regressão
-, e sim a tabela com as variáveis de \(x_1\) até \(x_5\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Modelo do R}
\KeywordTok{lm}\NormalTok{(}\DataTypeTok{formula =}\NormalTok{ y }\OperatorTok{~}\NormalTok{., }\DataTypeTok{data =}\NormalTok{ tabela01)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ ., data = tabela01)
## 
## Coefficients:
## (Intercept)           x1           x2           x3           x4           x5  
##    30.59320     -0.38612     -0.04556      0.31074     -0.37168      0.01410
\end{verbatim}

Segue abaixo a equação para o modelo determinado:

\(y= 30.59320 - 0.38612x1 - 0.04556x2 + 0.31074x3 - 0.37168x4 + 0.01410x5\)

\hypertarget{teste-de-significancia-da-regressuxe3o}{%
\subsection{Teste de significancia da
Regressão}\label{teste-de-significancia-da-regressuxe3o}}

A estimação de \(\sigma^2\) é necessária para o seguimento do teste.
Sendo assim, fazemos:

\(SQ_{res}=\boldsymbol{Y}^{T}\boldsymbol{Y}-\widehat{\boldsymbol{\beta}}^{T}\boldsymbol{X}^{T}\boldsymbol{Y}\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SQRes <-}\StringTok{ }\NormalTok{(}\KeywordTok{t}\NormalTok{(Y)}\OperatorTok{%*%}\NormalTok{Y)}\OperatorTok{-}\NormalTok{(}\KeywordTok{t}\NormalTok{(betas)}\OperatorTok{%*%}\KeywordTok{t}\NormalTok{(X)}\OperatorTok{%*%}\NormalTok{Y)}
\NormalTok{SQRes}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 3222.907
\end{verbatim}

Logo, \(\widehat{\sigma}^2=\dfrac{SQres}{n-p}\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p <-}\StringTok{ }\KeywordTok{ncol}\NormalTok{(X)}

\CommentTok{#estimando o sigma^2}

\NormalTok{sigma2 <-}\StringTok{ }\NormalTok{SQRes}\OperatorTok{/}\NormalTok{(n}\OperatorTok{-}\NormalTok{p)}
\NormalTok{sigma2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 153.4718
\end{verbatim}

\hypertarget{anova}{%
\subsection{ANOVA}\label{anova}}

Agora que ajustamos um modelo inicial, é necessário que verifiquemos se
ele é adequado em explicar a variabilidade de nossa amostra. Vamos
assumir que \(\xi\sim N_n(0,\sigma^2I)\). Precisamos agora verificar
nossa suposição graficamente:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Obtendo uma estimativa para Y a partir do modelo ajustado}
\NormalTok{Y_est <-}\StringTok{ }\NormalTok{X}\OperatorTok{%*%}\NormalTok{betas}

\CommentTok{# Cálculo dos resíduos}
\NormalTok{res <-}\StringTok{ }\NormalTok{Y }\OperatorTok{-}\StringTok{ }\NormalTok{Y_est}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{tibble}\NormalTok{(res), }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{sample =}\NormalTok{ res)) }\OperatorTok{+}\StringTok{ }\KeywordTok{stat_qq}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{stat_qq_line}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Amostra"}\NormalTok{,}
       \DataTypeTok{y =} \StringTok{"Quantis Teóricos",}
\StringTok{       title = "}\NormalTok{Normal Q}\OperatorTok{-}\NormalTok{Q Plot}\StringTok{") +}
\StringTok{  theme_pubclean()}

\StringTok{q <- ggplot(tibble(res), aes(res)) +}
\StringTok{  geom_histogram(aes(y=..density..), binwidth = 4, stat = "}\NormalTok{bin}\StringTok{") +}
\StringTok{  labs(title = "}\NormalTok{Histograma dos resíduos}\StringTok{",}
\StringTok{       y = "}\NormalTok{Densidade}\StringTok{",}
\StringTok{       x = "}\NormalTok{Valor}\StringTok{") +}
\StringTok{  theme_pubclean()}

\StringTok{grid.arrange(p,q, ncol = 2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Exercicio_2_SME0820_Grupo03_files/figure-latex/unnamed-chunk-11-1.pdf}

Interpretando os gráficos acima, podemos observar no histograma que a
distribuição - embora majoritariamente centralizada - ocorre de forma
irregular. No gráfico de dispersão podemos constatar certa normalidade
dos valores, que possuem uma aproximação evidente dos quantis teóricos.
Como estamos fazendo suposições a partir de uma análise interpretativa,
podemos utilizar do teste de Shapiro-Wilk para verificá-las, como segue
abaixo:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pander}\NormalTok{(}\KeywordTok{shapiro.test}\NormalTok{(res), }\DataTypeTok{style=}\StringTok{'rmarkdown'}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Teste de normalidade Shapiro-Wilk para os resíduos"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}cc@{}}
\caption{Teste de normalidade Shapiro-Wilk para os resíduos Se
considerarmos a significância como sendo 97\% - como referenciado em
materiais anteriores -, teremos que nosso modelo segue a distribuição
normal, visto que obtivemos um resultado de 0.2733 no teste de
Shapiro-Wilk. Ou seja, não é um valor alto suficiente para rejeitar a
hipótese nula de normalidade dos dados.}\tabularnewline
\toprule
Test statistic & P value\tabularnewline
\midrule
\endfirsthead
\toprule
Test statistic & P value\tabularnewline
\midrule
\endhead
0.9544 & 0.2733\tabularnewline
\bottomrule
\end{longtable}

Além disso, para determinar matematicamente se existe uma relação linear
entre a variável resposta \(\boldsymbol{Y}\) e qualquer as outras
covariáveis \(\boldsymbol{X}_1,\ldots,\boldsymbol{X}_k\), é possível
utilizar o teste \textbf{ANOVA}. Nele, queremos testar:

\textbf{\(H_0\)}: Nenhuma das variáveis contribui significativamente ao
modelo, versus:

\textbf{\(H_a\)}: Pelo menos uma das covariáveis contribui
significativamente ao modelo.

Tabela \emph{ANOVA}:

\begin{longtable}[]{@{}ccccc@{}}
\caption{Tabela ANOVA}\tabularnewline
\toprule
\textbf{F.V.} & \textbf{G.L} & \textbf{S.Q.} & \textbf{Q.M.} &
\textbf{F}\tabularnewline
\midrule
\endfirsthead
\toprule
\textbf{F.V.} & \textbf{G.L} & \textbf{S.Q.} & \textbf{Q.M.} &
\textbf{F}\tabularnewline
\midrule
\endhead
\textbf{Regressão} & \(k\) & \(SQ_{reg}\) & \(QMreg=\dfrac{SQreg}{k}\) &
\(F=\dfrac{QMreg}{QMres}\)\tabularnewline
\textbf{Resíduo} & \(n-p\) & \(SQ_{res}\) & \(QMres=\dfrac{SQres}{n-p}\)
&\tabularnewline
\textbf{Total} & \(n-1\) & \(SQ_{total}\) & \(QM_{Total}\)
&\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Soma dos quadrados dos residuos  }
\NormalTok{(SQRes <-}\StringTok{ }\KeywordTok{t}\NormalTok{(Y}\OperatorTok{-}\NormalTok{Y_est)}\OperatorTok{%*%}\NormalTok{(Y}\OperatorTok{-}\NormalTok{Y_est))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 3222.907
\end{verbatim}

\[SQ_{Reg} = SQ_{Total} - SQ_{Res} = \frac 1n \sum_{i=1}^n y_i^2 - (Y-\hat{Y})^T\cdot(Y-\hat{Y}) =\]
\[\beta^T \cdot X^T \cdot Y - \frac1n (u^T \cdot Y)^2\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Soma dos quadrados totais}
\NormalTok{u <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,n))}
\NormalTok{(SQTotal <-}\StringTok{ }\KeywordTok{t}\NormalTok{(Y)}\OperatorTok{%*%}\NormalTok{Y }\OperatorTok{-}\StringTok{ }\NormalTok{((}\KeywordTok{t}\NormalTok{(u)}\OperatorTok{%*%}\NormalTok{Y)}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 7870.112
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Soma dos quadrados da regressao  }
\NormalTok{(SQReg <-}\StringTok{ }\NormalTok{SQTotal }\OperatorTok{-}\StringTok{ }\NormalTok{SQRes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 4647.205
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Calculando a anova}

\NormalTok{k <-}\StringTok{ }\DecValTok{5} 
\NormalTok{p <-}\StringTok{ }\NormalTok{k}\OperatorTok{+}\DecValTok{1}


\NormalTok{gl_sqreg <-}\StringTok{ }\NormalTok{k}
\NormalTok{QMReg <-}\StringTok{ }\NormalTok{SQReg}\OperatorTok{/}\NormalTok{gl_sqreg}

\NormalTok{gl_sqres <-}\StringTok{ }\NormalTok{n}\OperatorTok{-}\NormalTok{p}
\NormalTok{QMRes <-}\StringTok{ }\NormalTok{SQRes}\OperatorTok{/}\NormalTok{gl_sqres}

\NormalTok{gl_sqtotal <-}\StringTok{ }\NormalTok{n}\DecValTok{-1}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#calculando a estatistica F}
\NormalTok{(F_}\DecValTok{0}\NormalTok{ <-}\StringTok{ }\NormalTok{QMReg}\OperatorTok{/}\NormalTok{QMRes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 6.056104
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(QMTotal <-}\StringTok{ }\NormalTok{QMRes }\OperatorTok{+}\StringTok{ }\NormalTok{QMReg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 1082.913
\end{verbatim}

Como nosso estimador \(F \sim F(k,\ n - k - 1)\), podemos obter os
quantis com o auxílio do R, assumindo \(\alpha = 0.03\) - a partir de
instruções fornecidas em trabalhos anteriores:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha <-}\StringTok{ }\FloatTok{0.03}
\NormalTok{(RR <-}\StringTok{ }\KeywordTok{qf}\NormalTok{(alpha, }\DataTypeTok{df1 =}\NormalTok{ k, }\DataTypeTok{df2 =}\NormalTok{ n }\OperatorTok{-}\StringTok{ }\NormalTok{k }\DecValTok{-1}\NormalTok{, }\DataTypeTok{lower.tail =}\NormalTok{ F) )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.098817
\end{verbatim}

Rejeitamos \(H_0\) se \(F_0 > F_{crit}\), sendo \(F_{crit}\) o quantil
teórico da distribuição F com \(k\) e \(n-p\) graus de liberdade.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{(RR }\OperatorTok{<}\StringTok{ }\NormalTok{F_}\DecValTok{0}\NormalTok{)\{}
  \KeywordTok{cat}\NormalTok{(}\StringTok{"Rejeita-se H0"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rejeita-se H0
\end{verbatim}

Dessa forma, podemos concluir com 97\% de confiança que pelo menos uma
das variáveis contribui significativamente ao modelo.

\hypertarget{verificando-a-importancia-do-subconjunto-com-x3-x4-e-x5.}{%
\section{Verificando a importancia do subconjunto com x3, x4 e
x5.}\label{verificando-a-importancia-do-subconjunto-com-x3-x4-e-x5.}}

\hypertarget{sob-h_0-ux3b2_2-0-vs-sob-h_1-ux3b2_2-neq-0}{%
\subsection{\texorpdfstring{Sob \(H_0 : β_2 = 0\) VS sob
\(H_1 : β_2 \neq 0:\)}{Sob H\_0 : β\_2 = 0 VS sob H\_1 : β\_2 \textbackslash neq 0:}}\label{sob-h_0-ux3b2_2-0-vs-sob-h_1-ux3b2_2-neq-0}}

Soma de quadrados extra devido a \(x_3\),\(x_4\) e \(x_5\):

\(SQ_{reg}(\beta_3,\beta_4,\beta_5|\beta_0,\beta_1,\beta_2) = SQ_{reg}(\beta_0,\beta_1,\beta_2,\beta_3,\beta_4,\beta_5) - SQ_{reg}(\beta_0,\beta_1,\beta_2)\)
(Não corrigida)

\(SQ_{reg}(\beta_3,\beta_4,\beta_5|\beta_0,\beta_1,\beta_2) = SQ_{reg}(\beta_1,\beta_2,\beta_3,\beta_4,\beta_5|\beta_0) - SQ_{reg}(\beta_1|\beta_0) - SQ_{reg}(\beta_2|\beta_1, \beta_0) - SQ_{reg}(\beta_3|\beta_2,\beta_1,\beta_0)- SQ_{reg}(\beta_4|\beta_3,\beta_2,\beta_1,\beta_0) - SQ_{reg}(\beta_5|\beta_4,\beta_3,\beta_2,\beta_1,\beta_0)\)
(Corrigida)

Temos que:

\(SQ_{reg}(\beta_0,\beta_1,\beta_2) = SQ_{reg}(\beta) = \widehat{\beta}^T X^T \boldsymbol{y}\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SQReg_r <-}\StringTok{ }\NormalTok{(}\KeywordTok{t}\NormalTok{(betas)}\OperatorTok{%*%}\KeywordTok{t}\NormalTok{(X)}\OperatorTok{%*%}\NormalTok{Y)}
\NormalTok{SQReg_r}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 21160.17
\end{verbatim}

e

\$SQ\_\{reg\}(\beta\_1,\beta\_2,\beta\_3,\beta\_4,\beta\_5\textbar{}\beta\_0)
= \widehat{\beta}\^{}T X\^{}T \boldsymbol{Y} -
\frac{(I_n^T\boldsymbol{Y})^2}{n} \$

coincide com o valor obtido na tabela ANOVA, sendo este:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SQReg }\CommentTok{# SQreg encontrado na tabela ANOVA}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 4647.205
\end{verbatim}

**

\(Y= \beta_0 + \beta_1X_1 + \beta_2X_2 + \xi\)

Sob \(H_0 : β_2 = 0\):

Considerando o modelo reduzido:

\(Y= \beta_1X_1 + \xi\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Sxx <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(x1}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\OperatorTok{-}\StringTok{ }\NormalTok{n}\OperatorTok{*}\NormalTok{(}\KeywordTok{mean}\NormalTok{(x1))}\OperatorTok{^}\DecValTok{2}
\NormalTok{Sxy <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(x1}\OperatorTok{*}\NormalTok{y) }\OperatorTok{-}\StringTok{ }\NormalTok{n}\OperatorTok{*}\NormalTok{(}\KeywordTok{mean}\NormalTok{(x1)}\OperatorTok{*}\KeywordTok{mean}\NormalTok{(y))}
\NormalTok{beta_est_modredu <-}\StringTok{ }\NormalTok{Sxy}\OperatorTok{/}\NormalTok{Sxx}
\NormalTok{beta_est_modredu}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.8650001
\end{verbatim}

Agora, tendo o modelo reduzido como sendo:

\(SQ_{reg} = \beta_1Sxy\)

podemos realizar:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SQReg_modredu <-}\StringTok{ }\NormalTok{beta_est_modredu}\OperatorTok{*}\NormalTok{Sxy}
\NormalTok{SQReg_modredu }\CommentTok{# 3 G.L. (3 covariáveis no subconjunto)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3909.467
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gl_modredu <-}\StringTok{ }\DecValTok{3}
\end{Highlighting}
\end{Shaded}

e, portanto,

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SQReg_teste <-}\StringTok{ }\NormalTok{SQReg}\OperatorTok{-}\NormalTok{SQReg_modredu}
\NormalTok{SQReg_teste}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 737.7382
\end{verbatim}

Este valor representa o aumento na \(SQ_{reg}\) com o acréscimo do
subconjunto no modelo que já possui \(X_1\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{QMReg_modredus <-}\StringTok{ }\NormalTok{(SQReg_teste}\OperatorTok{/}\NormalTok{gl_modredu)}
\NormalTok{F_testeparcial <-}\StringTok{ }\NormalTok{(QMReg_modredus}\OperatorTok{/}\NormalTok{QMRes)}
\NormalTok{F_testeparcial}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          [,1]
## [1,] 1.602332
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha <-}\StringTok{ }\FloatTok{0.03}
\NormalTok{RR <-}\StringTok{ }\KeywordTok{qf}\NormalTok{(alpha, }\DataTypeTok{df1 =}\NormalTok{ gl_modredu, }\DataTypeTok{df2 =}\NormalTok{ n }\OperatorTok{-}\StringTok{ }\NormalTok{gl_modredu }\DecValTok{-1}\NormalTok{, }\DataTypeTok{lower.tail =}\NormalTok{ F)}
\NormalTok{RR}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.556927
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{(RR }\OperatorTok{<}\StringTok{ }\NormalTok{F_testeparcial)\{}
 \KeywordTok{cat}\NormalTok{(}\StringTok{"Rejeita-se H0"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\end{document}
